### ISSUE TITLE
按照你的写法，为什么我两边的图片没有漏出一点呢

### ISSUE THREAD

**Issue by zhijieeeeee** [huazhiyuan2008/RecyclerViewCardGallery#2]
按照你的写法，为什么我两边的图片没有漏出一点呢

**Comment by huazhiyuan2008** [comment]
在adapter相应的位置调用

mCardAdapterHelper.onCreateViewHolder(parent, itemView);
mCardAdapterHelper.onBindViewHolder(holder.itemView, position, getItemCount());

别忘了这一步~ 这个步奏的作用就是Adapter中的view增加padding

**Comment by zhijieeeeee** [comment]
好的，谢谢，原来是我一个地方调用错了
