### ISSUE TITLE
Auto scrolling after some time

### ISSUE THREAD

**Issue by hardikamal** [huazhiyuan2008/RecyclerViewCardGallery#4]
Hi @huazhiyuan2008 
 
How can i implement auto scrolling after some duration.

Thanks

**Comment by huazhiyuan2008** [comment]
Use Handler+Runnable to call `RecyclerView.smoothScrollToPosition(mCurrentItemPos);`

**Comment by hardikamal** [comment]
Thanks for the prompt reply @huazhiyuan2008 
One more thing how can i make it cyclic. ie when the last item is visible add 1st item so that it continue scrolling to the left.

**Comment by huazhiyuan2008** [comment]
You can google how to implements infinite RecyclerView/ViewPager, then you will know it.

**Comment by hardikamal** [comment]
Cool thanks for the help and awesome library...
